[package]
name = "CorePackages"
author = "Roblox"
license = ""
version = "0.1.0"

[dependencies]
Roact = "roblox/roact@1.2"
Rodux = "roblox/rodux@1.0"
RoactRodux = "roblox/roact-rodux@0.2"
RoactNavigation = "roblox/roact-navigation@0.2"
Cryo = "roblox/cryo@1.0"
LuaChatDeps = { git = "https://github.rbx.com/Roblox/lua-chat-deps" }
LuaDiscussionsDeps = { git = "https://github.rbx.com/Roblox/lua-discussions-deps" }
LuaSocialLibrariesDeps = { git = "https://github.rbx.com/Roblox/lua-social-libraries-deps" }
UIBlox = { git = "https://github.rbx.com/Roblox/uiblox", rev = "master" }
Otter = "roblox/otter@0.1"
t = "osyris/t@1.0"
enumerate = "roblox/enumerate@1.0.0"

# The following packages were ported from AppTempCommon
Promise = { git = "https://github.rbx.com/Roblox/lua-promise" }
Result = { git = "https://github.rbx.com/Roblox/lua-result" }
tutils = { git = "https://github.rbx.com/Roblox/tutils" }

PurchasePrompt = { git = "https://github.rbx.com/esauer/purchase-prompt-migration", rev = "master"}

InGameMenuDependencies = { git = "https://github.rbx.com/Roblox/in-game-menu-dependencies", rev = "master" }

[dev_dependencies]
TestEZ = "roblox/testez@0.1.1"

[patch."https://github.com/roblox/roact"]
name = "roblox/roact"
version = "1.2"

[patch."https://github.com/roblox/cryo"]
name = "roblox/cryo"
version = "1.0"

[patch."https://github.com/roblox/t"]
name = "osyris/t"
version = "1.0"

[patch."https://github.com/roblox/rodux"]
name = "roblox/rodux"
version = "1.0"

[patch."https://github.com/roblox/roact-rodux"]
name = "roblox/roact-rodux"
version = "0.2"

[patch."https://github.com/roblox/otter"]
name = "roblox/otter"
version = "0.1"
